// Legacy offline snapshot utility only. Production now mounts the canonical release through /api/kompas/shell.
// Kompas is built in perfACT/copilot, not here. A hand-edited copy in this repo would drift from
// the app it claims to be, so public/kompas/ is only ever written by this script: styles.css verbatim and app.js with the reviewed voice reliability patch, index.html with the three changes it needs to live under MarketFit.
//
//     node scripts/sync-kompas.mjs            # source: ../../Daily jobright/perfACT/copilot
//     KOMPAS_SRC=/path/to/copilot node scripts/sync-kompas.mjs
//
// The copilot calls its engine at /api/<name>. MarketFit already owns /api/prep, so those calls are
// moved to /kompas/api/<name>, which next.config.js forwards to the copilot's own backend. The
// engine is not copied: there is one answer engine, and it lives with the copilot.

import { readFile, writeFile, mkdir, copyFile } from "node:fs/promises"
import { patchKompasVoice } from "./patch-kompas-voice.mjs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
const SRC = path.resolve(ROOT, process.env.KOMPAS_SRC || "../../Daily jobright/perfACT/copilot")
const OUT = path.join(ROOT, "public", "kompas")

function replaceOnce(html, find, replacement) {
  if (!html.includes(find)) throw new Error(`index.html no longer contains ${JSON.stringify(find)}; update sync-kompas.mjs`)
  return html.replace(find, replacement)
}

const API_SHIM = `<script>
/* MarketFit: the copilot's /api/* calls go to /kompas/api/*, forwarded to the copilot backend. */
(function () {
  var f = window.fetch;
  window.fetch = function (u, o) {
    if (typeof u === "string" && u.indexOf("/api/") === 0) u = "/kompas" + u;
    return f.call(this, u, o);
  };
})();
</script>`

const BACK_LINK = `<a class="side-item" href="/dashboard/prep" style="text-decoration:none"><span class="si-ico">←</span><span>Back to MarketFit</span></a>
    `

await mkdir(OUT, { recursive: true })
await writeFile(path.join(OUT, "app.js"), patchKompasVoice(await readFile(path.join(SRC, "app.js"), "utf8")), "utf8")
await copyFile(path.join(SRC, "styles.css"), path.join(OUT, "styles.css"))

let html = await readFile(path.join(SRC, "index.html"), "utf8")
html = replaceOnce(html, `href="styles.css"`, `href="/kompas/styles.css"`)
html = replaceOnce(html, `<script src="app.js"></script>`, `${API_SHIM}\n<script src="/kompas/app.js"></script>`)
html = replaceOnce(html, `<button class="side-item side-logout"`, `${BACK_LINK}<button class="side-item side-logout"`)
const NOTE = `<!-- Generated by scripts/sync-kompas.mjs from perfACT/copilot. Edit the copilot there and re-run; changes made here are overwritten. -->`
html = /^\s*<!doctype[^>]*>/i.test(html) ? html.replace(/^(\s*<!doctype[^>]*>)/i, `$1\n${NOTE}`) : `${NOTE}\n${html}`
await writeFile(path.join(OUT, "index.html"), html, "utf8")

console.log(`Kompas synced from ${SRC} -> ${path.relative(ROOT, OUT)}`)
